datasource.original.driver-class-name: com.mysql.cj.jdbc.Driver
datasource.original.url: jdbc:mysql://localhost:3306/test
datasource.original.username: root
datasource.original.password: root

datasource.camunda.driver-class-name: com.mysql.cj.jdbc.Driver
datasource.camunda.url: jdbc:mysql://localhost:3306/camunda
datasource.camunda.username: root
datasource.camunda.password: root



spring:
  jpa:
    generate-ddl: true
  #  h2:
#    console:
#      enabled: true
#      path: /h2-console
  security:
    user:
      name: admin
      password: admin
#  datasource:
#    url: jdbc:mysql://localhost:3306/test
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#server:
#  port: 8080


#camunda.bpm:
#  admin-user:
#    id: camunda
#    password: camunda
#  database:
#    type: mysql
#    schema-update: create-drop

#    schema-name: act_test
#  metrics.enabled: false
#  history-level: auto